version: "3.9"

services:
  client:
    container_name: fullstack-youtube-client
    build: ./client
    command: npm run start
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_CLOUDINARY_API_URL=https://api.cloudinary.com/v1_1
      - REACT_APP_CLOUDINARY_NAME=
      - REACT_APP_CLOUDINARY_PRESET_IMAGES=images
      - REACT_APP_CLOUDINARY_PRESET_VIDEOS=videos
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  server:
    container_name: fullstack-youtube-server
    build: ./server
    command: npm run start:init
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://denis:password2023@database/youtube-clone
      - JWT_ACCESS_EXPIRESIN=15m
      - JWT_ACCESS_SECRET=Ls@M%mNw2%
      - JWT_REFRESH_EXPIRESIN=30d
      - JWT_REFRESH_SECRET=F4oq*M!jUX%cr@^
      - NODE_ENV=development
      - SERVER_PORT=4000
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./server:/app

  database:
    container_name: fullstack-youtube-database
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=youtube-clone
      - POSTGRES_USER=denis
      - POSTGRES_PASSWORD=password2023
    ports:
      - 8000:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  adminer:
    container_name: fullstack-youtube-adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 9000:8080

volumes:
  database_data:
